#!/usr/bin/env python
import discord
import traceback
from discord.ext import commands


bot = commands.Bot(command_prefix='!', description='your description')


@bot.event
async def on_ready():
    print("Logged in as")
    print(bot.user.name)


async def on_error(event, *args, **kwargs):
    message = args[0]
    logging.warning(traceback.format_exc())
    await bot.send_message(message.channel, "Error".message)


@bot.command()
async def hello():
    await bot.say("Hello!")


@bot.command()
async def echo(*, message: str):
    await bot.say(message)


@bot.command(pass_context=True)
async def joined_at(ctx, member: discord.Member=None):
        if member is None:
            member = ctx.message.author
        await bot.say('{0} joined at {0.joined_at}'.format(member))


bot.run('Mzc5NjE3MTE2ODI5MTIyNTYy.DOsphg.KKpAmMT2uaLHQwsJZEcoJ9A89Eg')
